// Courses
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const DELETE_COURSE_OPTIMISTIC = 'DELETE_COURSE_OPTIMISTIC';

// Authors
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_AUTHOR_SUCCESS = 'CREATE_AUTHOR_SUCCESS';
export const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS';
export const DELETE_AUTHOR_OPTIMISTIC = 'DELETE_AUTHOR_OPTIMISTIC';

// Api
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

// Pagination
export const PAGINATION_COURSES_PAGE = 'PAGINATION_COURSES_PAGE';
export const PAGINATION_COURSES_ITEMSPERPAGE =
  'PAGINATION_COURSES_ITEMSPERPAGE';
export const PAGINATION_AUTHORS_PAGE = 'PAGINATION_AUTHORS_PAGE';
export const PAGINATION_AUTHORS_ITEMSPERPAGE =
  'PAGINATION_AUTHORS_ITEMSPERPAGE';

// Sorting
export const SORTING_COURSES_SORT = 'SORTING_COURSES_SORT';
export const SORTING_AUTHORS_SORT = 'SORTING_AUTHORS_SORT';

// Courses history
export const HISTORY_COURSES_CREATED = 'HISTORY_COURSES_CREATED';
export const HISTORY_COURSES_UPDATED = 'HISTORY_COURSES_UPDATED';
export const HISTORY_COURSES_DELETED = 'HISTORY_COURSES_DELETED';
export const HISTORY_COURSES_SELECTED = 'HISTORY_COURSES_SELECTED';

// Authors history
export const HISTORY_AUTHORS_CREATED = 'HISTORY_AUTHORS_CREATED';
export const HISTORY_AUTHORS_UPDATED = 'HISTORY_AUTHORS_UPDATED';
export const HISTORY_AUTHORS_DELETED = 'HISTORY_AUTHORS_DELETED';
export const HISTORY_AUTHORS_SELECTED = 'HISTORY_AUTHORS_SELECTED';
